import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath, URL } from "node:url";

import react from "@vitejs/plugin-react";
import { defineConfig } from "vitest/config";

/**
 * HTTPS for the dev server, when a local certificate happens to exist.
 *
 * **This is not a nicety — it is the difference between the PWA working and not.**
 * `getUserMedia` and `NDEFReader` are gated behind a browser secure context, so over
 * plain `http://<lan-ip>:5173` the camera never starts and Web NFC is absent. Every
 * scanning affordance silently disappears, which is exactly the "I see no indicator
 * when scanning" symptom: there is nothing to indicate, because the camera cannot be
 * asked for.
 *
 * ADR 0001 settled that production is `https://almagest.lan` behind a **private CA
 * installed on every phone**, because `.lan` cannot obtain a publicly-trusted
 * certificate. The same CA serves development.
 *
 * Generated by `make certs` into `certs/`, which is gitignored — those are real
 * private keys. **Absence is the normal case**: CI, a fresh clone and any other
 * machine have no `certs/`, so this must degrade to plain HTTP rather than fail to
 * boot. Hence `existsSync` rather than a config flag someone has to remember.
 */
const CERT_DIR = fileURLToPath(new URL("../certs", import.meta.url));
const KEY = `${CERT_DIR}/server.key`;
const CRT = `${CERT_DIR}/server.crt`;
const https =
  existsSync(KEY) && existsSync(CRT)
    ? { key: readFileSync(KEY), cert: readFileSync(CRT) }
    : undefined;

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: { "@": fileURLToPath(new URL("./src", import.meta.url)) },
  },
  server: {
    // Mobile-first: the PWA is developed on a phone on the LAN as much as on
    // this machine, so bind all interfaces rather than localhost only.
    host: true,
    ...(https === undefined ? {} : { https }),
    proxy: {
      "/api": { target: "http://127.0.0.1:8009", changeOrigin: true },
      // Regex, not the prefix "/s" — Vite matches proxy keys by prefix, so a
      // plain "/s" also swallows "/src/main.tsx" and every other module, which
      // silently proxies the whole app source to the API and renders a blank
      // page. The tag-tap path itself cannot move: it is physically written
      // into every NFC tag and printed QR.
      "^/s/[A-Za-z0-9-]+$": {
        target: "http://127.0.0.1:8009",
        changeOrigin: true,
      },
    },
  },
  test: {
    globals: true,
    environment: "jsdom",
    include: ["src/**/*.test.{ts,tsx}"],
    // Raises the suite's *patience* so it cannot be green at 12 cores and red at
    // 2 — see the reasoning in `src/test-setup.ts`, which sets Testing Library's
    // own `findBy*` budget. These two cover the outer per-test limit, which has
    // to exceed it or a slow assertion trips this instead.
    setupFiles: ["./src/test-setup.ts"],
    testTimeout: 15_000,
    hookTimeout: 15_000,
  },
});
