import {
  copyFileSync,
  createReadStream,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
} from "node:fs";
import { basename, join } from "node:path";
import { fileURLToPath, URL } from "node:url";

import react from "@vitejs/plugin-react";
import { defineConfig, type Plugin } from "vitest/config";

/**
 * HTTPS for the dev server, when a local certificate happens to exist.
 *
 * **This is not a nicety — it is the difference between the PWA working and not.**
 * `getUserMedia` and `NDEFReader` are gated behind a browser secure context, so over
 * plain `http://<lan-ip>:5173` the camera never starts and Web NFC is absent. Every
 * scanning affordance silently disappears, which is exactly the "I see no indicator
 * when scanning" symptom: there is nothing to indicate, because the camera cannot be
 * asked for.
 *
 * ADR 0001 settled that production is `https://almagest.lan` behind a **private CA
 * installed on every phone**, because `.lan` cannot obtain a publicly-trusted
 * certificate. The same CA serves development.
 *
 * Generated by `make certs` into `certs/`, which is gitignored — those are real
 * private keys. **Absence is the normal case**: CI, a fresh clone and any other
 * machine have no `certs/`, so this must degrade to plain HTTP rather than fail to
 * boot. Hence `existsSync` rather than a config flag someone has to remember.
 */
const CERT_DIR = fileURLToPath(new URL("../certs", import.meta.url));
const KEY = `${CERT_DIR}/server.key`;
const CRT = `${CERT_DIR}/server.crt`;
const https =
  existsSync(KEY) && existsSync(CRT)
    ? { key: readFileSync(KEY), cert: readFileSync(CRT) }
    : undefined;

/**
 * Serve the OCR runtime from our own origin, in dev and in the build.
 *
 * `tesseract.js` defaults every one of its three runtime assets — the worker
 * script, the core wasm, and the language model — to a jsDelivr CDN. That is the
 * same trap `src/lib/scan/decoder.ts` already sidestepped for `zxing-wasm`, and
 * for a reason spelled out there: this app is deployed on a LAN behind a private
 * CA with no promise of internet access, and a reader that only works when the
 * WAN is up is not a reader.
 *
 * Two of the three come from `node_modules` and are handled here rather than
 * checked in. The wasm cores are ~3 MB *each* and there are several variants
 * (`tesseract.js` picks one at runtime from what the browser's SIMD support
 * allows), so committing them would put ~9 MB of build output into every clone
 * for ever and pin it to one library version by hand. Copying them at build time
 * costs nothing in git and cannot drift from the installed package.
 *
 * The third — `public/tessdata/eng.traineddata.gz`, ~1.9 MB — *is* checked in,
 * because it is not in any package: it is data, it never changes, and a build
 * step that reaches out to GitHub to fetch it would reintroduce exactly the
 * network dependency this plugin exists to remove.
 *
 * Only the `-lstm` variants are copied. The legacy Tesseract engine needs a
 * different, much larger model and this app never asks for it (`legacyCore` and
 * `legacyLang` are both left off in `src/lib/capture/ocr.ts`), so shipping its
 * cores would be several megabytes serving nothing.
 */
const OCR_CORE_DIR = fileURLToPath(new URL("./node_modules/tesseract.js-core", import.meta.url));
const OCR_WORKER = fileURLToPath(
  new URL("./node_modules/tesseract.js/dist/worker.min.js", import.meta.url),
);
/** Where the browser asks for them. Mirrored by `ocr.ts`, which builds the same paths. */
const OCR_BASE = "/ocr";

function ocrRuntimeFiles(): string[] {
  if (!existsSync(OCR_CORE_DIR)) {
    return [];
  }
  // `readdirSync` rather than a hardcoded list: which variants ship is the
  // package's business, and a hardcoded name that disappears in a minor release
  // would fail as "OCR silently never loads" rather than as a build error.
  return readdirSync(OCR_CORE_DIR)
    .filter(
      (name) =>
        name.includes("-lstm") &&
        // `foo.wasm` is the module; `foo.wasm.js` is the asm.js fallback for a
        // browser with no WebAssembly at all. That browser cannot reach this
        // feature anyway — `zxing-wasm` already makes wasm a hard requirement
        // for the scanner, so a client that could not run it has no camera
        // decode either. Skipping the fallbacks halves what is shipped.
        (name.endsWith(".wasm") || (name.endsWith(".js") && !name.endsWith(".wasm.js"))),
    )
    .map((name) => join(OCR_CORE_DIR, name))
    .concat(existsSync(OCR_WORKER) ? [OCR_WORKER] : []);
}

function ocrRuntime(): Plugin {
  return {
    name: "almagest-ocr-runtime",
    // Dev: stream them straight out of `node_modules`, so `pnpm dev` needs no
    // build step and no copy that can go stale mid-session.
    configureServer(server) {
      server.middlewares.use((request, response, next) => {
        const url = request.url ?? "";
        if (!url.startsWith(`${OCR_BASE}/`)) {
          next();
          return;
        }
        const name = basename(url.split("?")[0] ?? "");
        const source = ocrRuntimeFiles().find((file) => basename(file) === name);
        if (source === undefined) {
          next();
          return;
        }
        response.setHeader(
          "Content-Type",
          name.endsWith(".wasm") ? "application/wasm" : "text/javascript",
        );
        createReadStream(source).pipe(response);
      });
    },
    // Build: copy into `dist/ocr/`. `writeBundle` rather than `emitFile` because
    // these are opaque runtime assets fetched by URL at runtime, not modules in
    // the graph — running them through the bundler would rewrite nothing useful
    // and mangle the worker's own `importScripts`.
    writeBundle(options) {
      const outDir = options.dir ?? fileURLToPath(new URL("./dist", import.meta.url));
      const target = join(outDir, OCR_BASE.slice(1));
      mkdirSync(target, { recursive: true });
      const sources = ocrRuntimeFiles();
      // Loud, because the failure it replaces is silent and only visible in
      // production: an empty `dist/ocr/` builds and deploys perfectly and then
      // every capture reports "the text reader could not be loaded". This
      // already happened once — `tesseract.js-core` is a *transitive* dependency
      // and pnpm does not link one at `node_modules/`, so the directory probe
      // found nothing and the plugin cheerfully copied zero files. It is a
      // direct dependency now, and this is what stops the next such change from
      // being discovered by a person holding a reel.
      if (sources.length === 0) {
        throw new Error(
          "almagest-ocr-runtime: found no tesseract.js runtime files to copy. " +
            `Expected them under ${OCR_CORE_DIR}. Is 'tesseract.js-core' installed?`,
        );
      }
      for (const source of sources) {
        copyFileSync(source, join(target, basename(source)));
      }
    },
  };
}

export default defineConfig({
  plugins: [react(), ocrRuntime()],
  resolve: {
    alias: { "@": fileURLToPath(new URL("./src", import.meta.url)) },
  },
  server: {
    // Mobile-first: the PWA is developed on a phone on the LAN as much as on
    // this machine, so bind all interfaces rather than localhost only.
    host: true,
    ...(https === undefined ? {} : { https }),
    proxy: {
      "/api": { target: "http://127.0.0.1:8000", changeOrigin: true },
      // Regex, not the prefix "/s" — Vite matches proxy keys by prefix, so a
      // plain "/s" also swallows "/src/main.tsx" and every other module, which
      // silently proxies the whole app source to the API and renders a blank
      // page. The tag-tap path itself cannot move: it is physically written
      // into every NFC tag and printed QR.
      "^/s/[A-Za-z0-9-]+$": {
        target: "http://127.0.0.1:8000",
        changeOrigin: true,
      },
    },
  },
  test: {
    globals: true,
    environment: "jsdom",
    include: ["src/**/*.test.{ts,tsx}"],
    // Raises the suite's *patience* so it cannot be green at 12 cores and red at
    // 2 — see the reasoning in `src/test-setup.ts`, which sets Testing Library's
    // own `findBy*` budget. These two cover the outer per-test limit, which has
    // to exceed it or a slow assertion trips this instead.
    setupFiles: ["./src/test-setup.ts"],
    testTimeout: 15_000,
    hookTimeout: 15_000,
  },
});
