/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/resolve/{short_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolve Short Id
         * @description Machine-readable resolution, for the PWA and `deviceagent`.
         */
        get: operations["resolve_short_id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/parts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Parts By Querystring */
        get: operations["search_parts_by_querystring"];
        put?: never;
        /** Search Parts */
        post: operations["search_parts"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** FilterIn */
        FilterIn: {
            /**
             * Template
             * @description `parameter_template.name`, e.g. 'capacitance'
             */
            template: string;
            /**
             * Value
             * @description Interpreted according to the template. Numeric templates accept the full shorthand grammar ('4k7', '20-30uF', '>=50V'); enum templates accept a choice key or any alias, comma-separated for OR.
             */
            value: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Database */
            database: string;
            /** Schema Revision */
            schema_revision: string | null;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** PartSummary */
        PartSummary: {
            /** Category Id */
            category_id: number | null;
            /** Description */
            description: string | null;
            /** Id */
            id: number;
            /** Is Stub */
            is_stub: boolean;
            /** Mpn */
            mpn: string | null;
            /** Name */
            name: string;
        };
        /** ResolveResponse */
        ResolveResponse: {
            /** Normalized */
            normalized?: string | null;
            /** Status */
            status: string;
            target?: components["schemas"]["ResolvedTarget"] | null;
        };
        /** ResolvedTarget */
        ResolvedTarget: {
            /** Display */
            display: string;
            /** Entity Pk */
            entity_pk: number;
            /** Entity Type */
            entity_type: string;
            /** Label */
            label: string;
            /** Label Path */
            label_path?: string | null;
            /** Short Id */
            short_id: string;
        };
        /** SearchRequest */
        SearchRequest: {
            /**
             * Category
             * @description Category slug; includes descendants
             */
            category?: string | null;
            /** Filters */
            filters?: components["schemas"]["FilterIn"][];
            /**
             * In Stock Only
             * @default false
             */
            in_stock_only?: boolean;
            /**
             * Include Stubs
             * @default true
             */
            include_stubs?: boolean;
            /**
             * Limit
             * @default 50
             */
            limit?: number;
            /**
             * Mode
             * @description 'search' matches a requirement; 'substitute' finds parts that would satisfy it, using each template's substitution_direction.
             * @default search
             * @enum {string}
             */
            mode?: "search" | "substitute";
            /**
             * Offset
             * @default 0
             */
            offset?: number;
            /** Part Kind */
            part_kind?: string | null;
            /** Text */
            text?: string | null;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Results */
            results: components["schemas"]["PartSummary"][];
            /** Total */
            total: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    resolve_short_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                short_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_parts_by_querystring: {
        parameters: {
            query?: {
                /** @description Repeatable `template:value`, e.g. `f=capacitance:20-30uF&f=mounting_type:THT` */
                f?: string[];
                text?: string | null;
                category?: string | null;
                part_kind?: string | null;
                in_stock_only?: boolean;
                include_stubs?: boolean;
                mode?: "search" | "substitute";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_parts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
