"""provisioning action log for the walk cursor and undo

Entirely additive: one new table, no backfill, and nothing existing touched.
`docs/PLAN.md` says "no stored cursor anywhere", and this table is not one — it
records what each step of a walk *did*. The cursor and the undo stack are both
derived from it, which is what makes a half-finished cabinet free to resume and
immune to anything bound out of band.

Two facts genuinely need persisting and only two: what a move displaced (the
`location_tags` row is gone by the time undo runs, so restoring it means having
kept a copy), and that a slot was skipped (a skipped slot still has no tag, so a
cursor reading only `location_tags` would walk straight back onto it).

Revision ID: fc96c545ee2f
Revises: 4cada779f255
Create Date: 2026-07-28 17:40:33.916613+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fc96c545ee2f"
down_revision: Union[str, Sequence[str], None] = "4cada779f255"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "provisioning_actions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("tag_uid", sa.String(length=32), nullable=True),
        sa.Column("ndef_url", sa.Text(), nullable=True),
        sa.Column("prior_location_id", sa.Integer(), nullable=True),
        sa.Column("prior_tag_uid", sa.String(length=32), nullable=True),
        sa.Column("prior_ndef_url", sa.Text(), nullable=True),
        sa.Column("prior_bind_source", sa.String(length=32), nullable=True),
        sa.Column("prior_written_at", sa.String(length=27), nullable=True),
        sa.Column("prior_is_read_only", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.String(length=27), nullable=False),
        sa.Column("undone_at", sa.String(length=27), nullable=True),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
            name=op.f("fk_provisioning_actions_location_id_locations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["prior_location_id"],
            ["locations.id"],
            name=op.f("fk_provisioning_actions_prior_location_id_locations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["provisioning_sessions.id"],
            name=op.f("fk_provisioning_actions_session_id_provisioning_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provisioning_actions")),
    )
    with op.batch_alter_table("provisioning_actions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_provisioning_actions_session_id_id", ["session_id", "id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("provisioning_actions", schema=None) as batch_op:
        batch_op.drop_index("ix_provisioning_actions_session_id_id")

    op.drop_table("provisioning_actions")
    # ### end Alembic commands ###
