"""capture dispatch queue on pending_intakes, and identity candidates

The capture-dispatch queue of ADR 0021: six columns and an index on
`pending_intakes`, plus the one genuinely tabular part, the identity candidates.

## There is no backfill, and that is the interesting difference

The research-queue migration (`1f24dee26b5f`) needed one, and needed it badly: its
`server_default='pending'` would have put every part that already had a datasheet
into the queue, and the first worker run would have re-researched several hundred
answered parts.

This migration's default is `not_requested`, so the same reasoning arrives at the
opposite conclusion — **every existing row is already correct.** A parked scan nobody
has asked to have read is exactly what an install upgrading to this schema contains,
and the state that says so is the default. Dispatching costs a GPU handover on a card
that is exclusive and co-tenanted, so an upgrade that silently enqueued every
photograph in the queue would be considerably worse here than the research case was:
not wasted egress, but a model resident on hardware a co-tenant needed.

`app.models.enums.DispatchState` argues the opt-in at length. The absence of an
`UPDATE` below is that argument's only trace in the schema, which is why it is written
down here.

## `intake_identity_candidates.source_text` is NOT NULL by design

Not merely because the model always fills it in. It is the reviewer's check against
the photograph — ADR 0021 records the quote catching an invented reading that was
otherwise indistinguishable from a correct one — and a nullable column would let a
future writer store a proposal nobody can review. `app.services.dispatch` additionally
refuses an *empty* one, which the schema alone cannot express without a `CHECK`, and
this schema has none anywhere (`CLAUDE.md`).

Revision ID: 3c812e78c49d
Revises: 6107f6b041da
Create Date: 2026-08-08 02:44:17.762493+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3c812e78c49d"
down_revision: Union[str, Sequence[str], None] = "6107f6b041da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "intake_identity_candidates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("intake_id", sa.Integer(), nullable=False),
        sa.Column("rank", sa.Integer(), server_default="0", nullable=False),
        sa.Column("mpn", sa.String(length=128), nullable=False),
        sa.Column("manufacturer", sa.String(length=128), nullable=True),
        sa.Column("package", sa.String(length=64), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("source_text", sa.String(length=500), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("part_id", sa.Integer(), nullable=True),
        sa.Column("provider", sa.String(length=64), nullable=True),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.String(length=27), nullable=False),
        sa.ForeignKeyConstraint(
            ["intake_id"],
            ["pending_intakes.id"],
            name=op.f("fk_intake_identity_candidates_intake_id_pending_intakes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["part_id"],
            ["parts.id"],
            name=op.f("fk_intake_identity_candidates_part_id_parts"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_intake_identity_candidates")),
        sa.UniqueConstraint("intake_id", "mpn", name="uq_intake_identity_candidates_intake_mpn"),
    )
    with op.batch_alter_table("intake_identity_candidates", schema=None) as batch_op:
        batch_op.create_index(
            "ix_intake_identity_candidates_intake", ["intake_id", "rank"], unique=False
        )

    with op.batch_alter_table("pending_intakes", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "dispatch_state",
                sa.String(length=32),
                server_default="not_requested",
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("dispatch_attempts", sa.Integer(), server_default="0", nullable=False)
        )
        batch_op.add_column(sa.Column("dispatch_claimed_at", sa.String(length=27), nullable=True))
        batch_op.add_column(sa.Column("dispatch_claimed_by", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("dispatch_error", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("dispatch_label_kind", sa.String(length=32), nullable=True))
        batch_op.create_index(
            "ix_pending_intakes_dispatch_queue",
            ["dispatch_state", "dispatch_attempts", "id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pending_intakes", schema=None) as batch_op:
        batch_op.drop_index("ix_pending_intakes_dispatch_queue")
        batch_op.drop_column("dispatch_label_kind")
        batch_op.drop_column("dispatch_error")
        batch_op.drop_column("dispatch_claimed_by")
        batch_op.drop_column("dispatch_claimed_at")
        batch_op.drop_column("dispatch_attempts")
        batch_op.drop_column("dispatch_state")

    with op.batch_alter_table("intake_identity_candidates", schema=None) as batch_op:
        batch_op.drop_index("ix_intake_identity_candidates_intake")

    op.drop_table("intake_identity_candidates")
    # ### end Alembic commands ###
