"""research queue on parts, and research candidates

The datasheet-research queue of ADR 0017: five columns and an index on `parts`,
plus the one genuinely tabular part, the candidates.

## The backfill is the whole reason this migration is not pure autogenerate

`research_state` lands with `server_default='pending'`, which is right for a part
created from here on. Applied to an existing install it is wrong for a large
fraction of rows: **every part that already has a primary datasheet would enter
the queue**, and the first worker run would go and research several hundred parts
that are already answered — burning egress and provider quota to rediscover URLs
already in the blob store, and very possibly *replacing* a hand-picked primary
datasheet with whatever a provider returned first.

So the second statement settles those parts `resolved` before anything can claim
them. It reads `document_links` directly rather than through the ORM, because a
migration must not import from `app` (`alembic/env.py` renders custom types as
`sa.String` precisely so a migration never depends on application code) — the
literals `'part'`, `'datasheet'` and `is_primary = 1` are `EntityType.PART`,
`DocumentRole.DATASHEET` and the primary flag, and they are spelled out here on
purpose.

Parts with a *non-primary* datasheet link stay `pending`, deliberately: a
reference sheet attached to a part is not the same as that part being specified,
and ADR 0017's whole argument is that finding the right document is the hard part.

`not_applicable` is not backfilled at all. Nothing in the schema distinguishes a
custom bracket from an unidentified passive, and guessing would silently exclude
real parts from research. A person marks those.

Revision ID: 1f24dee26b5f
Revises: d3b8e5f1a274
Create Date: 2026-08-04 20:12:45.682538+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1f24dee26b5f"
down_revision: Union[str, Sequence[str], None] = "d3b8e5f1a274"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "research_candidates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("part_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("reject_reason", sa.String(length=64), nullable=True),
        sa.Column("document_sha256", sa.String(length=64), nullable=True),
        sa.Column("rank", sa.Integer(), server_default="0", nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.String(length=27), nullable=False),
        sa.ForeignKeyConstraint(
            ["part_id"],
            ["parts.id"],
            name=op.f("fk_research_candidates_part_id_parts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_candidates")),
        sa.UniqueConstraint("part_id", "url", name="uq_research_candidates_part_url"),
    )
    with op.batch_alter_table("research_candidates", schema=None) as batch_op:
        batch_op.create_index("ix_research_candidates_part", ["part_id", "rank"], unique=False)

    with op.batch_alter_table("parts", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "research_state", sa.String(length=32), server_default="pending", nullable=False
            )
        )
        batch_op.add_column(
            sa.Column("research_attempts", sa.Integer(), server_default="0", nullable=False)
        )
        batch_op.add_column(sa.Column("research_claimed_at", sa.String(length=27), nullable=True))
        batch_op.add_column(sa.Column("research_claimed_by", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("research_error", sa.Text(), nullable=True))
        batch_op.create_index(
            "ix_parts_research_queue", ["research_state", "research_attempts", "id"], unique=False
        )

    # ### end Alembic commands ###

    # Settle every part that already has a primary datasheet, so the first worker
    # run does not re-research work that is already done. See the module docstring
    # for why this is not left to the server default.
    op.execute(
        """
        UPDATE parts SET research_state = 'resolved'
        WHERE id IN (
            SELECT entity_pk FROM document_links
            WHERE entity_type = 'part' AND role = 'datasheet' AND is_primary = 1
        )
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("parts", schema=None) as batch_op:
        batch_op.drop_index("ix_parts_research_queue")
        batch_op.drop_column("research_error")
        batch_op.drop_column("research_claimed_by")
        batch_op.drop_column("research_claimed_at")
        batch_op.drop_column("research_attempts")
        batch_op.drop_column("research_state")

    with op.batch_alter_table("research_candidates", schema=None) as batch_op:
        batch_op.drop_index("ix_research_candidates_part")

    op.drop_table("research_candidates")
    # ### end Alembic commands ###
