"""parameter value candidates and promotion

Revision ID: 904ad311d7f9
Revises: 760a2d6441d5
Create Date: 2026-07-29 04:44:23.777990+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "904ad311d7f9"
down_revision: Union[str, Sequence[str], None] = "760a2d6441d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


#: Two things about this table are deliberate and easy to "fix" into bugs.
#:
#: 1. The unique key is `(part_id, template_id, source, source_ref)`, **not**
#:    `(part_id, template_id)` as on `parameter_value`. Copying that constraint
#:    here would make it impossible to store two sources disagreeing about one
#:    field, which is the single most important thing this table exists to hold.
#:    What it does guarantee is one row per *observation*, so re-running the same
#:    extraction updates its row instead of accumulating a duplicate — and the
#:    promotion rules count agreeing sources from these rows, so duplicates
#:    would manufacture a consensus out of one observation.
#: 2. `source_ref` is NOT NULL with an empty-string default because NULLs
#:    compare distinct inside a UNIQUE index in SQLite. A nullable column would
#:    let unlimited rows share the same `(part, template, source)` while the
#:    constraint still looked present — the exact failure it is there to stop.
#:
#: `source`, `status` and `review_reason` are plain VARCHAR with no CHECK, as
#: everywhere else: a new provider or a new review reason must stay a one-line
#: change in `app.models.enums` and never a rebuild of a populated table.


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parameter_value_candidate",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("part_id", sa.Integer(), nullable=False),
        sa.Column("template_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("source_ref", sa.String(length=255), server_default="", nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("raw_value", sa.Text(), nullable=False),
        sa.Column("value_nominal", sa.Float(), nullable=True),
        sa.Column("value_min", sa.Float(), nullable=True),
        sa.Column("value_max", sa.Float(), nullable=True),
        sa.Column("choice_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), server_default="pending", nullable=False),
        sa.Column("review_reason", sa.String(length=32), nullable=True),
        sa.Column("requires_human", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.String(length=27), nullable=False),
        sa.Column("decided_at", sa.String(length=27), nullable=True),
        sa.ForeignKeyConstraint(
            ["choice_id"],
            ["parameter_choice.id"],
            name=op.f("fk_parameter_value_candidate_choice_id_parameter_choice"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["part_id"],
            ["parts.id"],
            name=op.f("fk_parameter_value_candidate_part_id_parts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["parameter_template.id"],
            name=op.f("fk_parameter_value_candidate_template_id_parameter_template"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_parameter_value_candidate")),
        sa.UniqueConstraint(
            "part_id",
            "template_id",
            "source",
            "source_ref",
            name="uq_parameter_value_candidate_observation",
        ),
    )
    with op.batch_alter_table("parameter_value_candidate", schema=None) as batch_op:
        batch_op.create_index("ix_pvc_part_template", ["part_id", "template_id"], unique=False)
        batch_op.create_index(
            "ix_pvc_pending",
            ["status", "created_at"],
            unique=False,
            sqlite_where=sa.text("status = 'pending'"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("parameter_value_candidate", schema=None) as batch_op:
        batch_op.drop_index("ix_pvc_pending", sqlite_where=sa.text("status = 'pending'"))
        batch_op.drop_index("ix_pvc_part_template")

    op.drop_table("parameter_value_candidate")
    # ### end Alembic commands ###
