"""label sheet jobs

Entirely additive: one new table, no backfill, nothing existing touched.

Records what `POST /api/labels/sheets` actually rendered — the grid geometry
a partial reprint (`slot_ids`) has to match to land in the right cell on an
already-cut sheet, and every card's placement, frozen at render time so `GET
/api/labels/sheets/{id}` never has to re-derive it from a tree that may have
moved on since. `label_prints` (existing) still gets one row per card; this
is "what one sheet run looked like" rather than "what got printed, ever".

Revision ID: d50a63bfbb00
Revises: fc96c545ee2f
Create Date: 2026-07-28 18:06:35.603790+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d50a63bfbb00"
down_revision: Union[str, Sequence[str], None] = "fc96c545ee2f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "label_sheet_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("template", sa.String(length=32), nullable=False),
        sa.Column("backend", sa.String(length=32), nullable=False),
        sa.Column("dpi", sa.Integer(), nullable=False),
        sa.Column("root_location_id", sa.Integer(), nullable=False),
        sa.Column("requested_slot_ids_json", sa.Text(), nullable=True),
        sa.Column("card_width_mm", sa.Float(), nullable=False),
        sa.Column("card_height_mm", sa.Float(), nullable=False),
        sa.Column("item_count", sa.Integer(), nullable=False),
        sa.Column("output_path", sa.Text(), nullable=False),
        sa.Column("placements_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.String(length=27), nullable=False),
        sa.Column("updated_at", sa.String(length=27), nullable=False),
        sa.ForeignKeyConstraint(
            ["root_location_id"],
            ["locations.id"],
            name=op.f("fk_label_sheet_jobs_root_location_id_locations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_label_sheet_jobs")),
    )
    with op.batch_alter_table("label_sheet_jobs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_label_sheet_jobs_root_location_id"), ["root_location_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("label_sheet_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_label_sheet_jobs_root_location_id"))

    op.drop_table("label_sheet_jobs")
    # ### end Alembic commands ###
