"""projects, BOM lines and derived stock allocations

Revision ID: 760a2d6441d5
Revises: 6bb14f048f8c
Create Date: 2026-07-28 23:15:58.891545+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "760a2d6441d5"
down_revision: Union[str, Sequence[str], None] = "6bb14f048f8c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


#: **The reserved cache survives a delete, not only a state change.**
#:
#: `stock_lots.qty_reserved_milli_cached` is maintained beside every write in
#: `app.services.reservations`, but a delete never goes through that service:
#: `stock_allocations.build_id` is `ON DELETE CASCADE`, so removing a build (or a
#: project, through its builds) drops `RESERVED` rows without anything
#: decrementing the counter, and the lot is left hiding real stock behind a hold
#: nothing can release. Reproduced before this trigger existed: reserve 4000,
#: delete the build, cached stays 4000 while the recomputation says 0.
#:
#: A trigger rather than an ORM `before_delete` hook because the cascade is a DB
#: action — no ORM event fires for the rows SQLite removes on its own, and
#: neither would one for a repair script working in SQL. The `state` literal is
#: spelled out rather than imported: a migration must never depend on
#: application code, and `ix_stock_allocations_reserved_lot` already writes the
#: same literal for the same reason.
#:
#: Verified against `RESERVED_SUM_SQL`, whose predicate this mirrors exactly:
#: only `state = 'reserved'` rows are in the sum, so only those decrement.
_ALLOCATION_TRIGGERS = (
    """
    CREATE TRIGGER trg_stock_allocations_deleted_reserved
    AFTER DELETE ON stock_allocations
    WHEN OLD.state = 'reserved' AND OLD.lot_id IS NOT NULL
    BEGIN
        UPDATE stock_lots
           SET qty_reserved_milli_cached = qty_reserved_milli_cached - OLD.qty_milli
         WHERE id = OLD.lot_id;
    END
    """,
)

_ALLOCATION_TRIGGER_NAMES = ("trg_stock_allocations_deleted_reserved",)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("revision", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=32), server_default="planning", nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("source_ref", sa.String(length=512), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.String(length=27), nullable=False),
        sa.Column("updated_at", sa.String(length=27), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_table(
        "project_builds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("build_no", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=128), nullable=True),
        sa.Column("assembly_count", sa.Integer(), server_default="1", nullable=False),
        sa.Column("bom_revision", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=32), server_default="planned", nullable=False),
        sa.Column("started_at", sa.String(length=27), nullable=True),
        sa.Column("completed_at", sa.String(length=27), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.String(length=27), nullable=False),
        sa.Column("updated_at", sa.String(length=27), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_builds_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_builds")),
        sa.UniqueConstraint(
            "project_id", "build_no", name=op.f("uq_project_builds_project_id_build_no")
        ),
    )
    with op.batch_alter_table("project_builds", schema=None) as batch_op:
        batch_op.create_index(
            "ix_project_builds_project_status", ["project_id", "status"], unique=False
        )

    op.create_table(
        "bom_lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("line_no", sa.Integer(), server_default="0", nullable=False),
        sa.Column("designators", sa.String(length=1024), nullable=True),
        sa.Column("qty_per_assembly_milli", sa.Integer(), nullable=False),
        sa.Column("part_id", sa.Integer(), nullable=True),
        sa.Column("is_match_confirmed", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("is_dnp", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("ref_value", sa.String(length=128), nullable=True),
        sa.Column("footprint", sa.String(length=128), nullable=True),
        sa.Column("mpn_raw", sa.String(length=128), nullable=True),
        sa.Column("mpn_norm", sa.String(length=128), nullable=True),
        sa.Column("manufacturer_raw", sa.String(length=128), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("raw_fields_json", sa.Text(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.String(length=27), nullable=False),
        sa.Column("updated_at", sa.String(length=27), nullable=False),
        sa.ForeignKeyConstraint(
            ["part_id"], ["parts.id"], name=op.f("fk_bom_lines_part_id_parts"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_bom_lines_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bom_lines")),
    )
    with op.batch_alter_table("bom_lines", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bom_lines_mpn_norm"), ["mpn_norm"], unique=False)
        batch_op.create_index(batch_op.f("ix_bom_lines_part_id"), ["part_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_bom_lines_project_id"), ["project_id"], unique=False)
        batch_op.create_index(
            "ix_bom_lines_unmatched",
            ["project_id", "line_no"],
            unique=False,
            sqlite_where=sa.text("part_id IS NULL"),
        )

    op.create_table(
        "bom_line_substitutes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bom_line_id", sa.Integer(), nullable=False),
        sa.Column("part_id", sa.Integer(), nullable=False),
        sa.Column("preference", sa.Integer(), server_default="0", nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.String(length=27), nullable=False),
        sa.ForeignKeyConstraint(
            ["bom_line_id"],
            ["bom_lines.id"],
            name=op.f("fk_bom_line_substitutes_bom_line_id_bom_lines"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["part_id"],
            ["parts.id"],
            name=op.f("fk_bom_line_substitutes_part_id_parts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bom_line_substitutes")),
        sa.UniqueConstraint(
            "bom_line_id", "part_id", name=op.f("uq_bom_line_substitutes_bom_line_id_part_id")
        ),
    )
    with op.batch_alter_table("bom_line_substitutes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_bom_line_substitutes_part_id"), ["part_id"], unique=False
        )

    op.create_table(
        "stock_allocations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("bom_line_id", sa.Integer(), nullable=True),
        sa.Column("part_id", sa.Integer(), nullable=False),
        sa.Column("lot_id", sa.Integer(), nullable=True),
        sa.Column("qty_milli", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=32), server_default="planned", nullable=False),
        sa.Column("consumed_ledger_seq", sa.Integer(), nullable=True),
        sa.Column("reserved_at", sa.String(length=27), nullable=True),
        sa.Column("consumed_at", sa.String(length=27), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.String(length=27), nullable=False),
        sa.Column("updated_at", sa.String(length=27), nullable=False),
        sa.ForeignKeyConstraint(
            ["bom_line_id"],
            ["bom_lines.id"],
            name=op.f("fk_stock_allocations_bom_line_id_bom_lines"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["build_id"],
            ["project_builds.id"],
            name=op.f("fk_stock_allocations_build_id_project_builds"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["consumed_ledger_seq"],
            ["stock_ledger.seq"],
            name=op.f("fk_stock_allocations_consumed_ledger_seq_stock_ledger"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["lot_id"],
            ["stock_lots.id"],
            name=op.f("fk_stock_allocations_lot_id_stock_lots"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["part_id"],
            ["parts.id"],
            name=op.f("fk_stock_allocations_part_id_parts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_allocations")),
    )
    with op.batch_alter_table("stock_allocations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_stock_allocations_bom_line_id"), ["bom_line_id"], unique=False
        )
        batch_op.create_index(
            "ix_stock_allocations_build_state", ["build_id", "state"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_stock_allocations_lot_id"), ["lot_id"], unique=False)
        batch_op.create_index("ix_stock_allocations_part_state", ["part_id", "state"], unique=False)
        batch_op.create_index(
            "ix_stock_allocations_reserved_lot",
            ["lot_id", "qty_milli"],
            unique=False,
            sqlite_where=sa.text("state = 'reserved'"),
        )

    # ### end Alembic commands ###

    for statement in _ALLOCATION_TRIGGERS:
        op.execute(statement)


def downgrade() -> None:
    """Downgrade schema."""
    for name in _ALLOCATION_TRIGGER_NAMES:
        op.execute(f"DROP TRIGGER IF EXISTS {name}")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stock_allocations", schema=None) as batch_op:
        batch_op.drop_index(
            "ix_stock_allocations_reserved_lot", sqlite_where=sa.text("state = 'reserved'")
        )
        batch_op.drop_index("ix_stock_allocations_part_state")
        batch_op.drop_index(batch_op.f("ix_stock_allocations_lot_id"))
        batch_op.drop_index("ix_stock_allocations_build_state")
        batch_op.drop_index(batch_op.f("ix_stock_allocations_bom_line_id"))

    op.drop_table("stock_allocations")
    with op.batch_alter_table("bom_line_substitutes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bom_line_substitutes_part_id"))

    op.drop_table("bom_line_substitutes")
    with op.batch_alter_table("bom_lines", schema=None) as batch_op:
        batch_op.drop_index("ix_bom_lines_unmatched", sqlite_where=sa.text("part_id IS NULL"))
        batch_op.drop_index(batch_op.f("ix_bom_lines_project_id"))
        batch_op.drop_index(batch_op.f("ix_bom_lines_part_id"))
        batch_op.drop_index(batch_op.f("ix_bom_lines_mpn_norm"))

    op.drop_table("bom_lines")
    with op.batch_alter_table("project_builds", schema=None) as batch_op:
        batch_op.drop_index("ix_project_builds_project_status")

    op.drop_table("project_builds")
    op.drop_table("projects")
    # ### end Alembic commands ###
