"""capacity and auto-assignment

Adds `location_occupancy` (cached fill state) and `layout_suggestions` (defrag
proposals), the triggers that keep occupancy dirty flags correct, and two
reference rows the new services depend on:

* the permanent `INBOX` staging location (`locations.is_staging`) —
  `app.services.assignment`'s escalation ladder always terminates there, so it
  must exist in every database, not just ones that ran a demo seed script.
* the `esd-sensitive` tag — `app.services.assignment` reads ESD-sensitivity
  off a part via this well-known tag rather than a dedicated column, because
  `parts` deliberately carries almost nothing beyond `name`/`part_kind_id` so
  intake stays fast. See the module docstring in `app/services/assignment.py`.

Three triggers, hand-written because Alembic cannot see them in the models —
exactly the same reason `stock_ledger`'s append-only triggers live in the core
migration rather than in `app/models/stock.py`:

* `trg_locations_seed_occupancy` — every new location gets a fresh, dirty
  `location_occupancy` row the instant it exists, so a dirty flag never has
  nowhere to land.
* `trg_stock_ledger_dirty_occupancy` / `trg_stock_lots_dirty_occupancy` — mark
  the affected location *and every ancestor* dirty, per PLAN.md ("marked dirty
  by triggers on ledger insert and lot relocation ... for the affected
  location and all ancestors"). Ancestors are derived from `id_path` prefix
  matching, the same technique `TreeRepository` uses everywhere else, so no
  recursion is needed even inside a trigger body.

Revision ID: b8c9d4009bdd
Revises: 97ef1cee5888
Create Date: 2026-07-28 00:35:50.101437+00:00

"""

from datetime import UTC, datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b8c9d4009bdd"
down_revision: Union[str, Sequence[str], None] = "97ef1cee5888"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Matches app.models.types._ISO_FORMAT: fixed width, so lexicographic order is
# chronological order.
_ISO_FORMAT = "%Y-%m-%dT%H:%M:%S.%fZ"

# ---------------------------------------------------------------------------
# Occupancy triggers
# ---------------------------------------------------------------------------
# The ancestor lookup used by both dirtying triggers: everything whose
# id_path is a prefix of the affected location's id_path, which is exactly
# TreeRepository's own definition of "ancestors of X" (docs/PLAN.md, "Storage
# tree"). `self.id IN (...)` skips NULLs in the list automatically, which is
# what lets one statement handle every combination of from/to/lot-location
# being unset.
_ANCESTOR_LOCATION_IDS_OF = """
    SELECT ancestor.id
      FROM locations AS self
      JOIN locations AS ancestor ON self.id_path LIKE ancestor.id_path || '%'
     WHERE self.id IN ({ids})
"""

_OCCUPANCY_TRIGGERS = (
    """
    CREATE TRIGGER trg_locations_seed_occupancy
    AFTER INSERT ON locations
    BEGIN
        INSERT INTO location_occupancy
            (location_id, capacity_model, capacity, used, fill_ratio, is_full, is_dirty, computed_at)
        VALUES
            (NEW.id, 'none', NULL, 0, NULL, 0, 1, NULL);
    END
    """,
    f"""
    CREATE TRIGGER trg_stock_ledger_dirty_occupancy
    AFTER INSERT ON stock_ledger
    BEGIN
        UPDATE location_occupancy
           SET is_dirty = 1
         WHERE location_id IN (
            {_ANCESTOR_LOCATION_IDS_OF.format(
                ids="NEW.to_location_id, NEW.from_location_id, "
                "(SELECT location_id FROM stock_lots WHERE id = NEW.lot_id)"
            )}
         );
    END
    """,
    f"""
    CREATE TRIGGER trg_stock_lots_dirty_occupancy
    AFTER UPDATE OF location_id ON stock_lots
    WHEN OLD.location_id IS NOT NEW.location_id
    BEGIN
        UPDATE location_occupancy
           SET is_dirty = 1
         WHERE location_id IN (
            {_ANCESTOR_LOCATION_IDS_OF.format(ids="OLD.location_id, NEW.location_id")}
         );
    END
    """,
)

_OCCUPANCY_TRIGGER_NAMES = (
    "trg_locations_seed_occupancy",
    "trg_stock_ledger_dirty_occupancy",
    "trg_stock_lots_dirty_occupancy",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "layout_suggestions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="pending", nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=True),
        sa.Column("other_location_id", sa.Integer(), nullable=True),
        sa.Column("part_id", sa.Integer(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("move_plan_json", sa.Text(), nullable=True),
        sa.Column("detail_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.String(length=27), nullable=False),
        sa.Column("dismissed_at", sa.String(length=27), nullable=True),
        sa.Column("applied_at", sa.String(length=27), nullable=True),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
            name=op.f("fk_layout_suggestions_location_id_locations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["other_location_id"],
            ["locations.id"],
            name=op.f("fk_layout_suggestions_other_location_id_locations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["part_id"],
            ["parts.id"],
            name=op.f("fk_layout_suggestions_part_id_parts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_layout_suggestions")),
    )
    with op.batch_alter_table("layout_suggestions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_layout_suggestions_kind"), ["kind"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_layout_suggestions_location_id"), ["location_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_layout_suggestions_status"), ["status"], unique=False)
        batch_op.create_index(
            "uq_layout_suggestions_pending_overfull_location",
            ["location_id"],
            unique=True,
            sqlite_where=sa.text("status = 'pending' AND kind = 'overfull'"),
        )

    op.create_table(
        "location_occupancy",
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("capacity_model", sa.String(length=32), nullable=False),
        sa.Column("capacity", sa.Float(), nullable=True),
        sa.Column("used", sa.Float(), server_default="0", nullable=False),
        sa.Column("fill_ratio", sa.Float(), nullable=True),
        sa.Column("is_full", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("is_dirty", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("computed_at", sa.String(length=27), nullable=True),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
            name=op.f("fk_location_occupancy_location_id_locations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("location_id", name=op.f("pk_location_occupancy")),
    )
    with op.batch_alter_table("location_occupancy", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_location_occupancy_is_dirty"), ["is_dirty"], unique=False
        )

    # ### end Alembic commands ###

    for statement in _OCCUPANCY_TRIGGERS:
        op.execute(statement)

    _seed()


def _seed() -> None:
    """Reference rows the new services cannot function without.

    Runs *after* the triggers above, deliberately: inserting `INBOX` while
    `trg_locations_seed_occupancy` already exists means the seed row gets its
    `location_occupancy` row the normal way, exercising the trigger rather
    than special-casing it.
    """
    bind = op.get_bind()
    now = datetime.now(UTC).strftime(_ISO_FORMAT)

    bind.execute(
        sa.text("INSERT INTO tags (slug, display_name) VALUES ('esd-sensitive', 'ESD sensitive')")
    )

    # `locations` has NOT NULL columns (`sort_order`, `id_path`, `label_path`,
    # `created_at`, `updated_at`) with no server-side default for several of
    # them, so a raw INSERT has to supply every one explicitly — the ORM's
    # Python-side defaults (`TreeMixin`, `TimestampMixin`) never run here.
    # `id_path` needs the row's own id, which SQLite only assigns at insert
    # time, hence the two-step insert-then-fix-up via `last_insert_rowid()`.
    bind.execute(
        sa.text(
            "INSERT INTO locations"
            " (name, sort_order, access_score, is_overfull, is_staging, is_placeable,"
            "  depth, id_path, label_path, created_at, updated_at)"
            " VALUES"
            " ('INBOX', 0, 0.5, 0, 1, 1, 0, '', 'INBOX', :now, :now)"
        ),
        {"now": now},
    )
    bind.execute(
        sa.text(
            "UPDATE locations SET id_path = '/' || id || '/' WHERE id = last_insert_rowid()"
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    bind.execute(sa.text("DELETE FROM locations WHERE name = 'INBOX' AND is_staging = 1"))
    bind.execute(sa.text("DELETE FROM tags WHERE slug = 'esd-sensitive'"))

    for name in _OCCUPANCY_TRIGGER_NAMES:
        op.execute(f"DROP TRIGGER IF EXISTS {name}")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("location_occupancy", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_location_occupancy_is_dirty"))

    op.drop_table("location_occupancy")
    with op.batch_alter_table("layout_suggestions", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_layout_suggestions_pending_overfull_location",
            sqlite_where=sa.text("status = 'pending' AND kind = 'overfull'"),
        )
        batch_op.drop_index(batch_op.f("ix_layout_suggestions_status"))
        batch_op.drop_index(batch_op.f("ix_layout_suggestions_location_id"))
        batch_op.drop_index(batch_op.f("ix_layout_suggestions_kind"))

    op.drop_table("layout_suggestions")
    # ### end Alembic commands ###
