"""content-addressed document store

Revision ID: f4880900192b
Revises: 7a0024b06ca5
Create Date: 2026-07-29 07:05:17.494600+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f4880900192b"
down_revision: Union[str, Sequence[str], None] = "7a0024b06ca5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


#: Three things here are deliberate and easy to "fix" into bugs.
#:
#: 1. **`documents.sha256` is UNIQUE and that is the dedup mechanism**, not a
#:    sanity check. The upload path hashes the bytes, looks this column up, and
#:    only then decides whether to write anything — `docs/PLAN.md`'s "hash
#:    computed before write so dedup is free". Dropping the constraint would not
#:    merely permit duplicates, it would let two rows claim one file on disk.
#: 2. **`document_links.is_primary` has no unique index, partial or otherwise.**
#:    The rule is "a role with any links has exactly one primary", and a partial
#:    unique index would enforce only the *at most one* half. The half that
#:    actually breaks is *at least one* — detach the primary from a part that
#:    still has three other sheets and `GET /api/parts/{id}/datasheet` 404s while
#:    the datasheets are all still attached. That is repaired in
#:    `app.services.documents.detach` and asserted in the tests; an index here
#:    would look like the guarantee while covering the easy half of it.
#: 3. **`page_count` is nullable** on a column that looks derivable. Per
#:    `docs/adr/0005-extraction-runs-outside-the-api.md` the API never opens a
#:    PDF, so it is filled in later by a worker that is allowed never to run. A
#:    document with no page count is a first-class state, not a failed import.
#:
#: `kind`, `role` and `entity_type` are plain VARCHAR with no CHECK, as
#: everywhere else: a new document kind or a new link role stays a one-line
#: change in `app.models.enums` and never a rebuild of a populated table.


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("media_type", sa.String(length=128), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("storage_path", sa.String(length=255), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.String(length=27), nullable=False),
        sa.Column("updated_at", sa.String(length=27), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.UniqueConstraint("sha256", name=op.f("uq_documents_sha256")),
    )
    op.create_table(
        "document_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("entity_pk", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("is_primary", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("created_at", sa.String(length=27), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_links_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_links")),
        sa.UniqueConstraint(
            "document_id", "entity_type", "entity_pk", "role", name="uq_document_links_binding"
        ),
    )
    with op.batch_alter_table("document_links", schema=None) as batch_op:
        batch_op.create_index(
            "ix_document_links_entity", ["entity_type", "entity_pk", "role"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("document_links", schema=None) as batch_op:
        batch_op.drop_index("ix_document_links_entity")

    op.drop_table("document_links")
    op.drop_table("documents")
    # ### end Alembic commands ###
