"""core schema

Phase 1 tables, the ledger's append-only triggers, and the reference rows the
schema cannot function without.

Two things here are hand-written rather than autogenerated, because Alembic
cannot see either one in the models:

* the `stock_ledger` immutability triggers, which are the actual enforcement of
  the append-only invariant;
* the seed rows for `part_kinds`, `units` and `packagings`, which exist because
  `parts.part_kind_id` is NOT NULL and there would otherwise be no legal value
  to give it on a fresh database.

Note what is *absent*: not one `CHECK` constraint and not one `sa.Enum`. Every
enumerated column is a plain VARCHAR validated in Python. SQLite cannot alter a
`CHECK`, so a `CHECK` enum would turn "support a new kind of thing" into a full
table rebuild — and that single rule is what keeps every deferred feature in
PLAN.md purely additive.

Revision ID: 97ef1cee5888
Revises:
Create Date: 2026-07-27 23:46:05.931214+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "97ef1cee5888"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# ---------------------------------------------------------------------------
# Append-only enforcement
# ---------------------------------------------------------------------------
# By triggers, not convention. Convention guarantees that someone eventually
# writes a "just fix the typo" script, and a ledger that can be edited is not a
# ledger. Undo is a compensating row carrying `reversal_of_seq`, never a delete.
_LEDGER_TRIGGERS = (
    """
    CREATE TRIGGER trg_stock_ledger_no_update
    BEFORE UPDATE ON stock_ledger
    BEGIN
        SELECT RAISE(ABORT, 'stock_ledger is append-only: use a compensating row');
    END
    """,
    """
    CREATE TRIGGER trg_stock_ledger_no_delete
    BEFORE DELETE ON stock_ledger
    BEGIN
        SELECT RAISE(ABORT, 'stock_ledger is append-only: use a compensating row');
    END
    """,
)

_LEDGER_TRIGGER_NAMES = ("trg_stock_ledger_no_update", "trg_stock_ledger_no_delete")

# ---------------------------------------------------------------------------
# Reference data
# ---------------------------------------------------------------------------
# Non-component inventory (tools, screws, cables) is in scope from the start,
# which is why this is a table rather than a boolean on `parts`.
_PART_KINDS = [
    {"slug": "component", "display_name": "Component", "sort_order": 10},
    {"slug": "module", "display_name": "Module / breakout", "sort_order": 20},
    {"slug": "mechanical", "display_name": "Mechanical / fastener", "sort_order": 30},
    {"slug": "cable", "display_name": "Cable / connector", "sort_order": 40},
    {"slug": "tool", "display_name": "Tool", "sort_order": 50},
    {"slug": "consumable", "display_name": "Consumable", "sort_order": 60},
    {"slug": "material", "display_name": "Raw material", "sort_order": 70},
]

# Quantities are stored as milli-units of whichever of these a part uses, so
# `is_divisible` drives validation and display only — never storage.
_UNITS = [
    {"slug": "each", "symbol": "pcs", "display_name": "Each", "is_divisible": 0},
    {"slug": "metre", "symbol": "m", "display_name": "Metre", "is_divisible": 1},
    {"slug": "gram", "symbol": "g", "display_name": "Gram", "is_divisible": 1},
    {"slug": "litre", "symbol": "L", "display_name": "Litre", "is_divisible": 1},
    {"slug": "pair", "symbol": "pr", "display_name": "Pair", "is_divisible": 0},
    {"slug": "set", "symbol": "set", "display_name": "Set", "is_divisible": 0},
]

# Packaging carries its own volume, which is what makes capacity
# packaging-aware with no separate regime: a reel occupies the reel's volume
# whether it holds 5000 parts or 12.
_PACKAGINGS = [
    {"code": "loose", "display_name": "Loose", "package_volume_mm3": None, "pitch_mm": None},
    {"code": "bag", "display_name": "Bag", "package_volume_mm3": None, "pitch_mm": None},
    {"code": "cut_tape", "display_name": "Cut tape", "package_volume_mm3": None, "pitch_mm": None},
    {"code": "reel", "display_name": "Reel", "package_volume_mm3": 1_200_000.0, "pitch_mm": 14.0},
    {"code": "tube", "display_name": "Tube", "package_volume_mm3": 60_000.0, "pitch_mm": 12.0},
    {"code": "tray", "display_name": "Tray", "package_volume_mm3": 400_000.0, "pitch_mm": None},
    {"code": "box", "display_name": "Box", "package_volume_mm3": None, "pitch_mm": None},
]

# Every derived cache in the schema is fully reconstructible from its source of
# truth. Registering them here means the nightly drift check has a row to write
# to on day one rather than needing to invent one.
_CACHES = ["lot_balances", "location_tree", "category_tree", "location_occupancy", "reservations"]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cache_state",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("is_dirty", sa.Integer(), nullable=False),
        sa.Column("last_rebuilt_at", sa.String(length=27), nullable=True),
        sa.Column("last_checked_at", sa.String(length=27), nullable=True),
        sa.Column("drift_count", sa.Integer(), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_cache_state")),
    )
    op.create_table(
        "client_operations",
        sa.Column("client_op_id", sa.String(length=36), nullable=False),
        sa.Column("device_id", sa.String(length=64), nullable=True),
        sa.Column("endpoint", sa.String(length=255), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("response_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.String(length=27), nullable=False),
        sa.PrimaryKeyConstraint("client_op_id", name=op.f("pk_client_operations")),
    )
    with op.batch_alter_table("client_operations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_client_operations_device_id"), ["device_id"], unique=False
        )

    op.create_table(
        "container_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("child_layout", sa.String(length=32), nullable=False),
        sa.Column("grid_rows", sa.Integer(), nullable=True),
        sa.Column("grid_cols", sa.Integer(), nullable=True),
        sa.Column("slot_label_scheme", sa.String(length=32), nullable=False),
        sa.Column("slot_label_params_json", sa.Text(), nullable=True),
        sa.Column("materialize_slots", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("capacity_model", sa.String(length=32), nullable=False),
        sa.Column("capacity_slots", sa.Integer(), nullable=True),
        sa.Column("max_parts_per_slot", sa.Integer(), nullable=True),
        sa.Column("inner_length_mm", sa.Float(), nullable=True),
        sa.Column("inner_width_mm", sa.Float(), nullable=True),
        sa.Column("inner_height_mm", sa.Float(), nullable=True),
        sa.Column("default_fill_factor", sa.Float(), server_default="0.55", nullable=False),
        sa.Column("full_threshold", sa.Float(), server_default="0.9", nullable=False),
        sa.Column("esd_safe", sa.Boolean(), nullable=True),
        sa.Column("is_placeable", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("max_item_dimension_mm", sa.Float(), nullable=True),
        sa.Column("allowed_part_kinds_json", sa.Text(), nullable=True),
        sa.Column("front_width_mm", sa.Float(), nullable=True),
        sa.Column("front_height_mm", sa.Float(), nullable=True),
        sa.Column("is_seed", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("created_at", sa.String(length=27), nullable=False),
        sa.Column("updated_at", sa.String(length=27), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_container_types")),
        sa.UniqueConstraint("slug", name=op.f("uq_container_types_slug")),
    )
    op.create_table(
        "manufacturers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("name_norm", sa.String(length=255), nullable=False),
        sa.Column("website", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_manufacturers")),
        sa.UniqueConstraint("name", name=op.f("uq_manufacturers_name")),
    )
    with op.batch_alter_table("manufacturers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_manufacturers_name_norm"), ["name_norm"], unique=False)

    op.create_table(
        "object_ids",
        sa.Column("short_id", sa.String(length=8), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("entity_pk", sa.Integer(), nullable=False),
        sa.Column("is_primary", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(length=27), nullable=False),
        sa.PrimaryKeyConstraint("short_id", name=op.f("pk_object_ids")),
    )
    with op.batch_alter_table("object_ids", schema=None) as batch_op:
        batch_op.create_index("ix_object_ids_entity", ["entity_type", "entity_pk"], unique=False)

    op.create_table(
        "package_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("imperial_code", sa.String(length=32), nullable=True),
        sa.Column("metric_code", sa.String(length=32), nullable=True),
        sa.Column("length_mm", sa.Float(), nullable=True),
        sa.Column("width_mm", sa.Float(), nullable=True),
        sa.Column("height_mm", sa.Float(), nullable=True),
        sa.Column("typical_mass_mg", sa.Float(), nullable=True),
        sa.Column("size_class", sa.String(length=32), nullable=True),
        sa.Column("is_tht", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_package_types")),
        sa.UniqueConstraint("slug", name=op.f("uq_package_types_slug")),
    )
    with op.batch_alter_table("package_types", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_package_types_imperial_code"), ["imperial_code"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_package_types_metric_code"), ["metric_code"], unique=False
        )

    op.create_table(
        "packagings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("display_name", sa.String(length=64), nullable=False),
        sa.Column("package_volume_mm3", sa.Float(), nullable=True),
        sa.Column("pitch_mm", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_packagings")),
        sa.UniqueConstraint("code", name=op.f("uq_packagings_code")),
    )
    op.create_table(
        "parameter_template",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("value_type", sa.String(length=32), nullable=False),
        sa.Column("base_unit", sa.String(length=64), nullable=True),
        sa.Column("applies_to_category", sa.String(length=255), nullable=True),
        sa.Column(
            "substitution_direction", sa.String(length=32), server_default="exact", nullable=False
        ),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("plausible_min", sa.Float(), nullable=True),
        sa.Column("plausible_max", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_parameter_template")),
        sa.UniqueConstraint("name", name=op.f("uq_parameter_template_name")),
    )
    op.create_table(
        "part_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("default_size_class", sa.String(length=32), nullable=True),
        sa.Column("default_fill_factor", sa.Float(), nullable=True),
        sa.Column("depth", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id_path", sa.String(length=1024), nullable=False),
        sa.Column("label_path", sa.Text(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.String(length=27), nullable=False),
        sa.Column("updated_at", sa.String(length=27), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["part_categories.id"],
            name=op.f("fk_part_categories_parent_id_part_categories"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_part_categories")),
        sa.UniqueConstraint("slug", name=op.f("uq_part_categories_slug")),
    )
    with op.batch_alter_table("part_categories", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_part_categories_id_path"), ["id_path"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_part_categories_parent_id"), ["parent_id"], unique=False
        )

    op.create_table(
        "part_kinds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_part_kinds")),
        sa.UniqueConstraint("slug", name=op.f("uq_part_kinds_slug")),
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value_json", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.String(length=27), nullable=False),
        sa.Column("updated_at", sa.String(length=27), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_settings")),
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("colour", sa.String(length=16), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tags")),
        sa.UniqueConstraint("slug", name=op.f("uq_tags_slug")),
    )
    op.create_table(
        "units",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=32), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("display_name", sa.String(length=64), nullable=False),
        sa.Column("is_divisible", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_units")),
        sa.UniqueConstraint("slug", name=op.f("uq_units_slug")),
    )
    op.create_table(
        "container_type_slot_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("container_type_id", sa.Integer(), nullable=False),
        sa.Column("slot_label", sa.String(length=64), nullable=False),
        sa.Column("row_idx", sa.Integer(), nullable=False),
        sa.Column("col_idx", sa.Integer(), nullable=False),
        sa.Column("row_span", sa.Integer(), server_default="1", nullable=False),
        sa.Column("col_span", sa.Integer(), server_default="1", nullable=False),
        sa.Column("size_class", sa.String(length=32), nullable=True),
        sa.Column("inner_volume_mm3", sa.Float(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["container_type_id"],
            ["container_types.id"],
            name=op.f("fk_container_type_slot_templates_container_type_id_container_types"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_container_type_slot_templates")),
        sa.UniqueConstraint(
            "container_type_id",
            "slot_label",
            name=op.f("uq_container_type_slot_templates_container_type_id_slot_label"),
        ),
    )
    with op.batch_alter_table("container_type_slot_templates", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_container_type_slot_templates_container_type_id"),
            ["container_type_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_slot_template_type_sort", ["container_type_id", "sort_order"], unique=False
        )

    op.create_table(
        "locations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("container_type_id", sa.Integer(), nullable=True),
        sa.Column("slot_label", sa.String(length=64), nullable=True),
        sa.Column("row_idx", sa.Integer(), nullable=True),
        sa.Column("col_idx", sa.Integer(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("esd_safe", sa.Boolean(), nullable=True),
        sa.Column("is_placeable", sa.Boolean(), nullable=True),
        sa.Column("fill_factor", sa.Float(), nullable=True),
        sa.Column("access_score", sa.Float(), server_default="0.5", nullable=False),
        sa.Column("is_overfull", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("is_staging", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("tare_mg", sa.Integer(), nullable=True),
        sa.Column("tare_sigma_mg", sa.Float(), nullable=True),
        sa.Column("tare_measured_at", sa.String(length=27), nullable=True),
        sa.Column("tare_source", sa.String(length=32), nullable=True),
        sa.Column("last_verified_at", sa.String(length=27), nullable=True),
        sa.Column("last_printed_at", sa.String(length=27), nullable=True),
        sa.Column("depth", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id_path", sa.String(length=1024), nullable=False),
        sa.Column("label_path", sa.Text(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.String(length=27), nullable=False),
        sa.Column("updated_at", sa.String(length=27), nullable=False),
        sa.ForeignKeyConstraint(
            ["container_type_id"],
            ["container_types.id"],
            name=op.f("fk_locations_container_type_id_container_types"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["locations.id"],
            name=op.f("fk_locations_parent_id_locations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_locations")),
    )
    with op.batch_alter_table("locations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_locations_container_type_id"), ["container_type_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_locations_id_path"), ["id_path"], unique=False)
        batch_op.create_index(batch_op.f("ix_locations_is_overfull"), ["is_overfull"], unique=False)
        batch_op.create_index(batch_op.f("ix_locations_is_staging"), ["is_staging"], unique=False)
        batch_op.create_index(batch_op.f("ix_locations_parent_id"), ["parent_id"], unique=False)
        batch_op.create_index("ix_locations_parent_sort", ["parent_id", "sort_order"], unique=False)
        batch_op.create_index(
            "uq_locations_parent_slot_label",
            ["parent_id", "slot_label"],
            unique=True,
            sqlite_where=sa.text("slot_label IS NOT NULL"),
        )

    op.create_table(
        "parameter_choice",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("template_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("aliases_json", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["parameter_template.id"],
            name=op.f("fk_parameter_choice_template_id_parameter_template"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_parameter_choice")),
        sa.UniqueConstraint("template_id", "key", name=op.f("uq_parameter_choice_template_id_key")),
    )
    with op.batch_alter_table("parameter_choice", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_parameter_choice_template_id"), ["template_id"], unique=False
        )

    op.create_table(
        "parts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("part_kind_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("mpn", sa.String(length=255), nullable=True),
        sa.Column("mpn_norm", sa.String(length=255), nullable=True),
        sa.Column("manufacturer_id", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("keywords", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("package_type_id", sa.Integer(), nullable=True),
        sa.Column("uom_id", sa.Integer(), nullable=True),
        sa.Column("is_stub", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("length_mm", sa.Float(), nullable=True),
        sa.Column("width_mm", sa.Float(), nullable=True),
        sa.Column("height_mm", sa.Float(), nullable=True),
        sa.Column("shape_factor", sa.Float(), nullable=True),
        sa.Column("unit_volume_mm3", sa.Float(), nullable=True),
        sa.Column("volume_source", sa.String(length=32), nullable=True),
        sa.Column("unit_mass_mg", sa.Float(), nullable=True),
        sa.Column("hot_score", sa.Float(), server_default="0", nullable=False),
        sa.Column("extra_specs_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.String(length=27), nullable=False),
        sa.Column("updated_at", sa.String(length=27), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["part_categories.id"],
            name=op.f("fk_parts_category_id_part_categories"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["manufacturer_id"],
            ["manufacturers.id"],
            name=op.f("fk_parts_manufacturer_id_manufacturers"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["package_type_id"],
            ["package_types.id"],
            name=op.f("fk_parts_package_type_id_package_types"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["part_kind_id"],
            ["part_kinds.id"],
            name=op.f("fk_parts_part_kind_id_part_kinds"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["uom_id"], ["units.id"], name=op.f("fk_parts_uom_id_units"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_parts")),
    )
    with op.batch_alter_table("parts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_parts_category_id"), ["category_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_parts_is_stub"), ["is_stub"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_parts_manufacturer_id"), ["manufacturer_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_parts_mpn"), ["mpn"], unique=False)
        batch_op.create_index(batch_op.f("ix_parts_mpn_norm"), ["mpn_norm"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_parts_package_type_id"), ["package_type_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_parts_part_kind_id"), ["part_kind_id"], unique=False)
        batch_op.create_index(
            "uq_parts_mpn_norm_manufacturer",
            ["mpn_norm", "manufacturer_id"],
            unique=True,
            sqlite_where=sa.text("mpn_norm IS NOT NULL"),
        )

    op.create_table(
        "location_tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("tag_uid", sa.String(length=32), nullable=True),
        sa.Column("ndef_url", sa.Text(), nullable=False),
        sa.Column("is_read_only", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("bind_source", sa.String(length=32), nullable=True),
        sa.Column("written_at", sa.String(length=27), nullable=False),
        sa.Column("last_verified_at", sa.String(length=27), nullable=True),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
            name=op.f("fk_location_tags_location_id_locations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_location_tags")),
        sa.UniqueConstraint("location_id", name=op.f("uq_location_tags_location_id")),
    )
    with op.batch_alter_table("location_tags", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_location_tags_tag_uid"), ["tag_uid"], unique=False)

    op.create_table(
        "parameter_value",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("part_id", sa.Integer(), nullable=False),
        sa.Column("template_id", sa.Integer(), nullable=False),
        sa.Column("raw_input", sa.Text(), nullable=False),
        sa.Column("value_nominal", sa.Float(), nullable=True),
        sa.Column("value_min", sa.Float(), nullable=True),
        sa.Column("value_max", sa.Float(), nullable=True),
        sa.Column("value_typ", sa.Float(), nullable=True),
        sa.Column("tolerance_pct", sa.Float(), nullable=True),
        sa.Column("display_mantissa", sa.Float(), nullable=True),
        sa.Column("display_si_prefix", sa.String(length=8), nullable=True),
        sa.Column("display_unit_symbol", sa.String(length=16), nullable=True),
        sa.Column("choice_id", sa.Integer(), nullable=True),
        sa.Column("value_text", sa.Text(), nullable=True),
        sa.Column("value_bool", sa.Integer(), nullable=True),
        sa.Column("provenance", sa.String(length=32), server_default="manual", nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["choice_id"],
            ["parameter_choice.id"],
            name=op.f("fk_parameter_value_choice_id_parameter_choice"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["part_id"],
            ["parts.id"],
            name=op.f("fk_parameter_value_part_id_parts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["parameter_template.id"],
            name=op.f("fk_parameter_value_template_id_parameter_template"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_parameter_value")),
        sa.UniqueConstraint("part_id", "template_id", name="uq_parameter_value_part_template"),
    )
    with op.batch_alter_table("parameter_value", schema=None) as batch_op:
        batch_op.create_index(
            "ix_pv_tmpl_ch",
            ["template_id", "choice_id"],
            unique=False,
            sqlite_where=sa.text("choice_id IS NOT NULL"),
        )
        batch_op.create_index(
            "ix_pv_tmpl_num",
            ["template_id", "value_nominal"],
            unique=False,
            sqlite_where=sa.text("value_nominal IS NOT NULL"),
        )
        batch_op.create_index(
            "ix_pv_tmpl_range",
            ["template_id", "value_min", "value_max"],
            unique=False,
            sqlite_where=sa.text("value_min IS NOT NULL"),
        )

    op.create_table(
        "part_substitutes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("part_id", sa.Integer(), nullable=False),
        sa.Column("substitute_part_id", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.String(length=27), nullable=False),
        sa.ForeignKeyConstraint(
            ["part_id"],
            ["parts.id"],
            name=op.f("fk_part_substitutes_part_id_parts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["substitute_part_id"],
            ["parts.id"],
            name=op.f("fk_part_substitutes_substitute_part_id_parts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_part_substitutes")),
        sa.UniqueConstraint(
            "part_id",
            "substitute_part_id",
            name=op.f("uq_part_substitutes_part_id_substitute_part_id"),
        ),
    )
    with op.batch_alter_table("part_substitutes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_part_substitutes_part_id"), ["part_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_part_substitutes_substitute_part_id"),
            ["substitute_part_id"],
            unique=False,
        )

    op.create_table(
        "part_tags",
        sa.Column("part_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["part_id"], ["parts.id"], name=op.f("fk_part_tags_part_id_parts"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tags.id"], name=op.f("fk_part_tags_tag_id_tags"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("part_id", "tag_id", name=op.f("pk_part_tags")),
    )
    op.create_table(
        "stock_lots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("part_id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("packaging_id", sa.Integer(), nullable=True),
        sa.Column("pack_nominal_qty_milli", sa.Integer(), nullable=True),
        sa.Column("batch_code", sa.String(length=128), nullable=True),
        sa.Column("serial", sa.String(length=128), nullable=True),
        sa.Column("date_code", sa.String(length=32), nullable=True),
        sa.Column("supplier_part_id", sa.Integer(), nullable=True),
        sa.Column("unit_cost_micro", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("qty_milli_cached", sa.Integer(), server_default="0", nullable=False),
        sa.Column("qty_reserved_milli_cached", sa.Integer(), server_default="0", nullable=False),
        sa.Column("slots_occupied", sa.Integer(), nullable=True),
        sa.Column("volume_mm3_cached", sa.Float(), nullable=True),
        sa.Column("container_tare_mg", sa.Integer(), nullable=True),
        sa.Column("opened_at", sa.String(length=27), nullable=True),
        sa.Column("expires_at", sa.String(length=27), nullable=True),
        sa.Column("retired_at", sa.String(length=27), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.String(length=27), nullable=False),
        sa.Column("updated_at", sa.String(length=27), nullable=False),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
            name=op.f("fk_stock_lots_location_id_locations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["packaging_id"],
            ["packagings.id"],
            name=op.f("fk_stock_lots_packaging_id_packagings"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["part_id"], ["parts.id"], name=op.f("fk_stock_lots_part_id_parts"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_lots")),
    )
    with op.batch_alter_table("stock_lots", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_stock_lots_batch_code"), ["batch_code"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_stock_lots_location_id"), ["location_id"], unique=False
        )
        batch_op.create_index(
            "ix_stock_lots_location_status", ["location_id", "status"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_stock_lots_part_id"), ["part_id"], unique=False)
        batch_op.create_index(
            "ix_stock_lots_part_location", ["part_id", "location_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_stock_lots_status"), ["status"], unique=False)

    op.create_table(
        "stock_ledger",
        sa.Column("seq", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ts", sa.String(length=27), nullable=False),
        sa.Column("lot_id", sa.Integer(), nullable=True),
        sa.Column("part_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("delta_milli", sa.Integer(), nullable=False),
        sa.Column("qty_after_milli", sa.Integer(), nullable=False),
        sa.Column("from_location_id", sa.Integer(), nullable=True),
        sa.Column("to_location_id", sa.Integer(), nullable=True),
        sa.Column("counted_qty_milli", sa.Integer(), nullable=True),
        sa.Column("measured_mass_mg", sa.Integer(), nullable=True),
        sa.Column("unit_cost_micro", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("ref_type", sa.String(length=32), nullable=True),
        sa.Column("ref_id", sa.Integer(), nullable=True),
        sa.Column("group_uuid", sa.String(length=36), nullable=True),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("reversal_of_seq", sa.Integer(), nullable=True),
        sa.Column("client_op_id", sa.String(length=36), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["from_location_id"],
            ["locations.id"],
            name=op.f("fk_stock_ledger_from_location_id_locations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["lot_id"],
            ["stock_lots.id"],
            name=op.f("fk_stock_ledger_lot_id_stock_lots"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["part_id"],
            ["parts.id"],
            name=op.f("fk_stock_ledger_part_id_parts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["to_location_id"],
            ["locations.id"],
            name=op.f("fk_stock_ledger_to_location_id_locations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("seq", name=op.f("pk_stock_ledger")),
        sa.UniqueConstraint("client_op_id", name=op.f("uq_stock_ledger_client_op_id")),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("stock_ledger", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_stock_ledger_group_uuid"), ["group_uuid"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_stock_ledger_kind"), ["kind"], unique=False)
        batch_op.create_index(batch_op.f("ix_stock_ledger_lot_id"), ["lot_id"], unique=False)
        batch_op.create_index("ix_stock_ledger_lot_seq", ["lot_id", "seq"], unique=False)
        batch_op.create_index(batch_op.f("ix_stock_ledger_part_id"), ["part_id"], unique=False)
        batch_op.create_index("ix_stock_ledger_part_ts", ["part_id", "ts"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_stock_ledger_reversal_of_seq"), ["reversal_of_seq"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_stock_ledger_ts"), ["ts"], unique=False)

    # ### end Alembic commands ###

    for statement in _LEDGER_TRIGGERS:
        op.execute(statement)

    _seed()


def _seed() -> None:
    """Reference rows the schema cannot function without.

    Distinct from `app.scripts.seed_demo`, which loads sample parts and example
    cabinets. These rows are structural: `parts.part_kind_id` is NOT NULL, so
    without `part_kinds` a fresh database cannot hold a single part.
    """
    bind = op.get_bind()

    bind.execute(
        sa.text(
            "INSERT INTO part_kinds (slug, display_name, sort_order)"
            " VALUES (:slug, :display_name, :sort_order)"
        ),
        _PART_KINDS,
    )
    bind.execute(
        sa.text(
            "INSERT INTO units (slug, symbol, display_name, is_divisible)"
            " VALUES (:slug, :symbol, :display_name, :is_divisible)"
        ),
        _UNITS,
    )
    bind.execute(
        sa.text(
            "INSERT INTO packagings (code, display_name, package_volume_mm3, pitch_mm)"
            " VALUES (:code, :display_name, :package_volume_mm3, :pitch_mm)"
        ),
        _PACKAGINGS,
    )
    bind.execute(
        sa.text("INSERT INTO cache_state (name, is_dirty, drift_count) VALUES (:name, 1, 0)"),
        [{"name": name} for name in _CACHES],
    )


def downgrade() -> None:
    """Downgrade schema."""
    for name in _LEDGER_TRIGGER_NAMES:
        op.execute(f"DROP TRIGGER IF EXISTS {name}")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stock_ledger", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_stock_ledger_ts"))
        batch_op.drop_index(batch_op.f("ix_stock_ledger_reversal_of_seq"))
        batch_op.drop_index("ix_stock_ledger_part_ts")
        batch_op.drop_index(batch_op.f("ix_stock_ledger_part_id"))
        batch_op.drop_index("ix_stock_ledger_lot_seq")
        batch_op.drop_index(batch_op.f("ix_stock_ledger_lot_id"))
        batch_op.drop_index(batch_op.f("ix_stock_ledger_kind"))
        batch_op.drop_index(batch_op.f("ix_stock_ledger_group_uuid"))

    op.drop_table("stock_ledger")
    with op.batch_alter_table("stock_lots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_stock_lots_status"))
        batch_op.drop_index("ix_stock_lots_part_location")
        batch_op.drop_index(batch_op.f("ix_stock_lots_part_id"))
        batch_op.drop_index("ix_stock_lots_location_status")
        batch_op.drop_index(batch_op.f("ix_stock_lots_location_id"))
        batch_op.drop_index(batch_op.f("ix_stock_lots_batch_code"))

    op.drop_table("stock_lots")
    op.drop_table("part_tags")
    with op.batch_alter_table("part_substitutes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_part_substitutes_substitute_part_id"))
        batch_op.drop_index(batch_op.f("ix_part_substitutes_part_id"))

    op.drop_table("part_substitutes")
    with op.batch_alter_table("parameter_value", schema=None) as batch_op:
        batch_op.drop_index("ix_pv_tmpl_range", sqlite_where=sa.text("value_min IS NOT NULL"))
        batch_op.drop_index("ix_pv_tmpl_num", sqlite_where=sa.text("value_nominal IS NOT NULL"))
        batch_op.drop_index("ix_pv_tmpl_ch", sqlite_where=sa.text("choice_id IS NOT NULL"))

    op.drop_table("parameter_value")
    with op.batch_alter_table("location_tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_location_tags_tag_uid"))

    op.drop_table("location_tags")
    with op.batch_alter_table("parts", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_parts_mpn_norm_manufacturer", sqlite_where=sa.text("mpn_norm IS NOT NULL")
        )
        batch_op.drop_index(batch_op.f("ix_parts_part_kind_id"))
        batch_op.drop_index(batch_op.f("ix_parts_package_type_id"))
        batch_op.drop_index(batch_op.f("ix_parts_mpn_norm"))
        batch_op.drop_index(batch_op.f("ix_parts_mpn"))
        batch_op.drop_index(batch_op.f("ix_parts_manufacturer_id"))
        batch_op.drop_index(batch_op.f("ix_parts_is_stub"))
        batch_op.drop_index(batch_op.f("ix_parts_category_id"))

    op.drop_table("parts")
    with op.batch_alter_table("parameter_choice", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_parameter_choice_template_id"))

    op.drop_table("parameter_choice")
    with op.batch_alter_table("locations", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_locations_parent_slot_label", sqlite_where=sa.text("slot_label IS NOT NULL")
        )
        batch_op.drop_index("ix_locations_parent_sort")
        batch_op.drop_index(batch_op.f("ix_locations_parent_id"))
        batch_op.drop_index(batch_op.f("ix_locations_is_staging"))
        batch_op.drop_index(batch_op.f("ix_locations_is_overfull"))
        batch_op.drop_index(batch_op.f("ix_locations_id_path"))
        batch_op.drop_index(batch_op.f("ix_locations_container_type_id"))

    op.drop_table("locations")
    with op.batch_alter_table("container_type_slot_templates", schema=None) as batch_op:
        batch_op.drop_index("ix_slot_template_type_sort")
        batch_op.drop_index(batch_op.f("ix_container_type_slot_templates_container_type_id"))

    op.drop_table("container_type_slot_templates")
    op.drop_table("units")
    op.drop_table("tags")
    op.drop_table("settings")
    op.drop_table("part_kinds")
    with op.batch_alter_table("part_categories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_part_categories_parent_id"))
        batch_op.drop_index(batch_op.f("ix_part_categories_id_path"))

    op.drop_table("part_categories")
    op.drop_table("parameter_template")
    op.drop_table("packagings")
    with op.batch_alter_table("package_types", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_package_types_metric_code"))
        batch_op.drop_index(batch_op.f("ix_package_types_imperial_code"))

    op.drop_table("package_types")
    with op.batch_alter_table("object_ids", schema=None) as batch_op:
        batch_op.drop_index("ix_object_ids_entity")

    op.drop_table("object_ids")
    with op.batch_alter_table("manufacturers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_manufacturers_name_norm"))

    op.drop_table("manufacturers")
    op.drop_table("container_types")
    with op.batch_alter_table("client_operations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_client_operations_device_id"))

    op.drop_table("client_operations")
    op.drop_table("cache_state")
    # ### end Alembic commands ###
