"""recursive container types, provisioning and label prints

Revision ID: 2455fce33ad7
Revises: dcfe797424e9
Create Date: 2026-07-28 16:12:16.697965+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2455fce33ad7"
down_revision: Union[str, Sequence[str], None] = "dcfe797424e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "label_prints",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("entity_pk", sa.Integer(), nullable=False),
        sa.Column("template", sa.String(length=64), nullable=False),
        sa.Column("backend", sa.String(length=32), nullable=False),
        sa.Column("dpi", sa.Integer(), nullable=True),
        sa.Column("width_mm", sa.Float(), nullable=True),
        sa.Column("height_mm", sa.Float(), nullable=True),
        sa.Column("succeeded", sa.Boolean(), nullable=False),
        sa.Column("job_ref", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.String(length=27), nullable=False),
        sa.Column("updated_at", sa.String(length=27), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_label_prints")),
    )
    with op.batch_alter_table("label_prints", schema=None) as batch_op:
        batch_op.create_index("ix_label_prints_entity", ["entity_type", "entity_pk"], unique=False)

    op.create_table(
        "container_type_physical",
        sa.Column("container_type_id", sa.Integer(), nullable=False),
        sa.Column("gridfinity_u_w", sa.Integer(), nullable=True),
        sa.Column("gridfinity_u_d", sa.Integer(), nullable=True),
        sa.Column("gridfinity_u_h", sa.Integer(), nullable=True),
        sa.Column("stl_ref", sa.Text(), nullable=True),
        sa.Column("generator", sa.String(length=64), nullable=True),
        sa.Column("generator_params_json", sa.Text(), nullable=True),
        sa.Column("tag_pocket", sa.String(length=32), nullable=False),
        sa.Column("label_slot_mm", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["container_type_id"],
            ["container_types.id"],
            name=op.f("fk_container_type_physical_container_type_id_container_types"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("container_type_id", name=op.f("pk_container_type_physical")),
    )
    op.create_table(
        "provisioning_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("root_location_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("device_kind", sa.String(length=32), nullable=True),
        sa.Column("started_at", sa.String(length=27), nullable=False),
        sa.Column("completed_at", sa.String(length=27), nullable=True),
        sa.Column("bound_count", sa.Integer(), nullable=False),
        sa.Column("skipped_count", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["root_location_id"],
            ["locations.id"],
            name=op.f("fk_provisioning_sessions_root_location_id_locations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provisioning_sessions")),
    )
    with op.batch_alter_table("provisioning_sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_provisioning_sessions_root_location_id"),
            ["root_location_id"],
            unique=False,
        )

    op.create_table(
        "verification_mismatches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("expected_tag_uid", sa.String(length=32), nullable=True),
        sa.Column("scanned_tag_uid", sa.String(length=32), nullable=False),
        sa.Column("scanned_resolved_location_id", sa.Integer(), nullable=True),
        sa.Column("resolved_at", sa.String(length=27), nullable=True),
        sa.Column("created_at", sa.String(length=27), nullable=False),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
            name=op.f("fk_verification_mismatches_location_id_locations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["scanned_resolved_location_id"],
            ["locations.id"],
            name=op.f("fk_verification_mismatches_scanned_resolved_location_id_locations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["provisioning_sessions.id"],
            name=op.f("fk_verification_mismatches_session_id_provisioning_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verification_mismatches")),
    )
    with op.batch_alter_table("verification_mismatches", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_verification_mismatches_session_id"), ["session_id"], unique=False
        )

    with op.batch_alter_table("container_types", schema=None) as batch_op:
        batch_op.add_column(sa.Column("grid_pitch_mm", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("grid_height_unit_mm", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("footprint_cols", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("footprint_rows", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("footprint_height_u", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("container_types", schema=None) as batch_op:
        batch_op.drop_column("footprint_height_u")
        batch_op.drop_column("footprint_rows")
        batch_op.drop_column("footprint_cols")
        batch_op.drop_column("grid_height_unit_mm")
        batch_op.drop_column("grid_pitch_mm")

    with op.batch_alter_table("verification_mismatches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_verification_mismatches_session_id"))

    op.drop_table("verification_mismatches")
    with op.batch_alter_table("provisioning_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_provisioning_sessions_root_location_id"))

    op.drop_table("provisioning_sessions")
    op.drop_table("container_type_physical")
    with op.batch_alter_table("label_prints", schema=None) as batch_op:
        batch_op.drop_index("ix_label_prints_entity")

    op.drop_table("label_prints")
    # ### end Alembic commands ###
