"""pending intake queue, so a parked scan survives the device

Revision ID: 6bb14f048f8c
Revises: d50a63bfbb00
Create Date: 2026-07-28 20:52:45.342950+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6bb14f048f8c"
down_revision: Union[str, Sequence[str], None] = "d50a63bfbb00"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pending_intakes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_op_id", sa.String(length=36), nullable=False),
        sa.Column("scan_event_id", sa.Integer(), nullable=True),
        sa.Column("raw_payload", sa.Text(), nullable=False),
        sa.Column("symbology", sa.String(length=32), nullable=True),
        sa.Column("decoded_kind", sa.String(length=32), nullable=True),
        sa.Column("mpn", sa.String(length=128), nullable=True),
        sa.Column("manufacturer", sa.String(length=128), nullable=True),
        sa.Column("supplier_part_number", sa.String(length=128), nullable=True),
        sa.Column("date_code", sa.String(length=32), nullable=True),
        sa.Column("lot_code", sa.String(length=128), nullable=True),
        sa.Column("quantity_milli", sa.Integer(), nullable=True),
        sa.Column("part_id", sa.Integer(), nullable=True),
        sa.Column("resolved_part_id", sa.Integer(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("device_id", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=32), server_default="pending", nullable=False),
        sa.Column("resolved_at", sa.String(length=27), nullable=True),
        sa.Column("queued_at", sa.String(length=27), nullable=True),
        sa.Column("created_at", sa.String(length=27), nullable=False),
        sa.Column("updated_at", sa.String(length=27), nullable=False),
        sa.ForeignKeyConstraint(
            ["part_id"],
            ["parts.id"],
            name=op.f("fk_pending_intakes_part_id_parts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_part_id"],
            ["parts.id"],
            name=op.f("fk_pending_intakes_resolved_part_id_parts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["scan_event_id"],
            ["scan_events.id"],
            name=op.f("fk_pending_intakes_scan_event_id_scan_events"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pending_intakes")),
        sa.UniqueConstraint("client_op_id", name=op.f("uq_pending_intakes_client_op_id")),
    )
    with op.batch_alter_table("pending_intakes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pending_intakes_part_id"), ["part_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_pending_intakes_scan_event_id"), ["scan_event_id"], unique=False
        )
        batch_op.create_index("ix_pending_intakes_status_id", ["status", "id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pending_intakes", schema=None) as batch_op:
        batch_op.drop_index("ix_pending_intakes_status_id")
        batch_op.drop_index(batch_op.f("ix_pending_intakes_scan_event_id"))
        batch_op.drop_index(batch_op.f("ix_pending_intakes_part_id"))

    op.drop_table("pending_intakes")
    # ### end Alembic commands ###
