"""model runs: the transcript of every model call

One table, and it is the first thing here that stores a *conversation* rather than
a conclusion. Everything else keeps what a model decided —
`intake_identity_candidates` the identities a vision run proposed,
`parameter_value_candidate` the fields an extraction run proposed — and none of it
keeps what the model was told or what it actually returned.

That gap is the reason for this table. `CLAUDE.md` forbids auto-accepting a
model-read part number and ADR 0021 makes `source_text` `NOT NULL` so a reviewer
can check the quote against the photograph; both concern *what the model said*.
The question that follows a wrong reading is *what was it told*, and until now
nothing could answer it. `app.models.runs` argues this at length.

## There is no backfill, and there cannot be

Nothing recorded these before, so every run that has already happened is
unrecoverable — the transcripts were never held anywhere, not even in a log this
process could read back. An install upgrading to this schema therefore has an
empty table and a history that starts now. That is the honest outcome and it is
worth writing down, because the alternative reading — "the table is empty, so the
worker is not recording" — is exactly the wrong conclusion for somebody to draw on
the first day after an upgrade.

The three columns that would have made a partial backfill imaginable point the
other way as well: `dispatch_error` holds the message but never the prompt,
`intake_identity_candidates.provider`/`model` say who answered but not what with,
and `documents.extraction_error` is the same shape. Reconstructing a prompt from a
stored error would be inventing one.

## Nullable is the interesting half of this schema

Six columns are nullable and each null is a distinct fact rather than a shrug:

* `latency_ms`, `prompt_tokens`, `completion_tokens`, `finish_reason` — the server
  did not report it. `usage` is optional in the OpenAI response shape and several
  local servers omit it. **None of them defaults to 0**, deliberately: a zero would
  read as "the prompt was empty" and would pull any average taken over these rows
  toward whichever servers were quiet. That is
  `app.services.enrichment.calls.CallStats`' own rule, kept intact at the column.
* `request_json` — the transport raised before it had built a payload.
* `response_text` — the call never reached a completion. Distinct from `""`, which
  would mean a server that answered with nothing.

## No triggers, unlike `stock_ledger`

Following `captures`' own paragraph on this: a run is a notebook entry, not a
ledger row. Nothing computes a balance from these, and deleting a stale transcript
has to stay a one-click mistake to fix rather than a compensating row.

The consequence is that **retention is unbounded and nothing prunes.** A drain of
forty photographs writes forty rows carrying a prompt and a completion each, and
`MAX_TRANSCRIPT_CHARS` bounds one row rather than the table. Fine at this scale,
not fine forever; the pruning pass is not written and this is where that is
admitted rather than implied.

## `intake_id` is `SET NULL`, and `document_sha256` is not a foreign key

`intake_identity_candidates.intake_id` cascades, because a proposal *about* an
entry is meaningless without it. A run is a different kind of fact: a model was
asked a question and it cost a GPU second, and deleting the entry does not un-spend
that. Same reasoning gives `document_sha256` no foreign key at all, exactly as
`research_candidates.document_sha256` has none — a pruned blob must not invalidate
the historical fact that this run read it.

Revision ID: 69e7b736c14e
Revises: 3c812e78c49d
Create Date: 2026-08-08 15:17:03.229674+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "69e7b736c14e"
down_revision: Union[str, Sequence[str], None] = "3c812e78c49d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("intake_id", sa.Integer(), nullable=True),
        sa.Column("document_sha256", sa.String(length=64), nullable=True),
        sa.Column("started_at", sa.String(length=27), nullable=False),
        sa.Column("finished_at", sa.String(length=27), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("finish_reason", sa.String(length=64), nullable=True),
        sa.Column("request_json", sa.Text(), nullable=True),
        sa.Column("response_text", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("truncated", sa.Boolean(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["intake_id"],
            ["pending_intakes.id"],
            name=op.f("fk_model_runs_intake_id_pending_intakes"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_runs")),
    )
    with op.batch_alter_table("model_runs", schema=None) as batch_op:
        batch_op.create_index("ix_model_runs_intake", ["intake_id", "started_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("model_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_model_runs_intake")

    op.drop_table("model_runs")
    # ### end Alembic commands ###
