"""staged parts and project staging locations

Revision ID: 7a0024b06ca5
Revises: 760a2d6441d5
Create Date: 2026-07-29 03:04:44.237331+00:00

ADR 0004. Two nullable columns and nothing else — no new table, no rebuilt
`stock_allocations.state`, because that column has never been a `CHECK`
constraint. `AllocationState.STAGED` is therefore a one-line change in Python
and costs this migration nothing at all, which is the second time that rule has
paid for itself outright.

**`batch_alter_table` on SQLite drops and recreates the table, and a recreated
table loses its triggers.** Alembic reflects and restores the indexes; it knows
nothing about `trg_stock_allocations_deleted_reserved`, created by the migration
that introduced `stock_allocations`. Losing it would silently reintroduce the
exact bug it was written for — a cascaded delete of a `RESERVED` row leaving
`stock_lots.qty_reserved_milli_cached` claiming a hold nothing can release — and
the loss would be invisible until a nightly drift check happened to fire. So it
is recreated below, verbatim, and **any future batch alteration of this table
must do the same.**

No data migration and no seeded row, unlike the `INBOX` this scheme reuses:
staging locations are created lazily on the first withdrawal
(`app.services.staging`). A `PROJECTS` root inserted here would show up in the
storage tree of every install that never stages anything, and ADR 0004 is
explicit that a project which never withdraws anything creates no clutter.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7a0024b06ca5"
down_revision: Union[str, Sequence[str], None] = "760a2d6441d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


#: Copied character for character from revision 760a2d6441d5, which is what
#: makes this a restoration rather than a second, subtly different definition of
#: the same rule. The `state` literal is spelled out for the same reason it is
#: there: a migration must never import from `app`.
_RESERVED_DELETE_TRIGGER = """
    CREATE TRIGGER trg_stock_allocations_deleted_reserved
    AFTER DELETE ON stock_allocations
    WHEN OLD.state = 'reserved' AND OLD.lot_id IS NOT NULL
    BEGIN
        UPDATE stock_lots
           SET qty_reserved_milli_cached = qty_reserved_milli_cached - OLD.qty_milli
         WHERE id = OLD.lot_id;
    END
"""


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_builds", schema=None) as batch_op:
        batch_op.add_column(sa.Column("staging_location_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_project_builds_staging_location_id_locations"),
            "locations",
            ["staging_location_id"],
            ["id"],
            ondelete="SET NULL",
        )

    with op.batch_alter_table("stock_allocations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("staged_ledger_seq", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_stock_allocations_staged_ledger_seq_stock_ledger"),
            "stock_ledger",
            ["staged_ledger_seq"],
            ["seq"],
            ondelete="RESTRICT",
        )

    # ### end Alembic commands ###

    # The table above was recreated, so its trigger went with it. See the module
    # docstring.
    op.execute("DROP TRIGGER IF EXISTS trg_stock_allocations_deleted_reserved")
    op.execute(_RESERVED_DELETE_TRIGGER)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stock_allocations", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_stock_allocations_staged_ledger_seq_stock_ledger"), type_="foreignkey"
        )
        batch_op.drop_column("staged_ledger_seq")

    with op.batch_alter_table("project_builds", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_project_builds_staging_location_id_locations"), type_="foreignkey"
        )
        batch_op.drop_column("staging_location_id")

    # ### end Alembic commands ###

    # Downgrading recreates the table too, and the revision this returns to
    # expects the trigger to exist — its own downgrade is what drops it.
    op.execute("DROP TRIGGER IF EXISTS trg_stock_allocations_deleted_reserved")
    op.execute(_RESERVED_DELETE_TRIGGER)
