"""extraction queue on documents

Revision ID: ad85ca219ffb
Revises: f4880900192b
Create Date: 2026-07-29 08:02:18.995808+00:00

ADR 0005. **Nine columns and one index — and no new table**, which is the point:
the ADR calls the work queue "a plain index, not a table", and
`ix_documents_extraction_queue` is that index. A queue table would be a second copy
of "which documents exist", kept in step with the first by a sweep, and the sweep is
what breaks.

The extracted **text is not here either.** It goes to `datasheet_fts(rowid =
documents.id)`, created by revision dcfe797424e9 for exactly this purpose and
documented there ("its rowid is the future documents.id ... datasheet text arrives
from an extraction pipeline, not by mirroring a column"). That table is contentful,
so it stores the text as well as indexing it, and one copy in the only structure
that can search it is the right number. It is legitimately a cache rather than
storage: the blob is the authority, extraction is a pure function of it, so losing
the index costs a re-run and never data.

Three columns look like they should be NOT NULL and are not, deliberately:

* `text_low_confidence` — **NULL means no judgement has been made.** `FALSE` by
  default would make an unread scanned datasheet look positively vouched for, which
  is the exact "empty and silently trusted" outcome the flag exists to prevent.
* `extracted_at` and `extractor` — NULL for a document nobody has read, which is the
  normal state of every PDF the moment it is stored. Per ADR 0005 a document with no
  extracted text is a first-class state, not a failed import.

`extraction_state` is plain VARCHAR with **no CHECK**, as everywhere in this schema.
That is what makes Phase 6's LLM stage riding the same queue a one-line addition to
`app.models.enums.ExtractionState` rather than a rebuild of a populated table.

`batch_alter_table` recreates the table on SQLite, which drops any triggers on it.
`documents` has none — it is not the ledger and it has no FTS mirror trigger (see
dcfe797424e9: `datasheet_fts` deliberately gets no trigger) — so there is nothing to
restore here. **A future batch alteration of this table must re-check that**, as the
staged-parts revision had to for `stock_allocations`.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ad85ca219ffb"
down_revision: Union[str, Sequence[str], None] = "f4880900192b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


#: Anything already stored that is not a PDF has no text layer to read, so the
#: `server_default` of 'pending' would be wrong for it: a tray photograph sitting in
#: the queue forever makes the queue depth stop meaning the depth of the work, and a
#: queue whose depth is not the work is a queue nobody trusts.
#:
#: The media type is spelled out rather than imported from
#: `app.services.document_text.EXTRACTABLE_MEDIA_TYPES` because **a migration must
#: never import from `app`** — the set may legitimately widen when an OCR extractor
#: lands, and this statement must keep describing what was true when it ran.
_MARK_UNEXTRACTABLE = """
    UPDATE documents
       SET extraction_state = 'not_applicable'
     WHERE media_type <> 'application/pdf'
"""


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "extraction_state", sa.String(length=32), server_default="pending", nullable=False
            )
        )
        batch_op.add_column(
            sa.Column("extraction_attempts", sa.Integer(), server_default="0", nullable=False)
        )
        batch_op.add_column(sa.Column("extraction_claimed_at", sa.String(length=27), nullable=True))
        batch_op.add_column(sa.Column("extraction_claimed_by", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("extracted_at", sa.String(length=27), nullable=True))
        batch_op.add_column(sa.Column("extractor", sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column("text_char_count", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("text_low_confidence", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("extraction_error", sa.Text(), nullable=True))
        batch_op.create_index(
            "ix_documents_extraction_queue",
            ["extraction_state", "extraction_attempts", "id"],
            unique=False,
        )

    # ### end Alembic commands ###

    op.execute(_MARK_UNEXTRACTABLE)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_index("ix_documents_extraction_queue")
        batch_op.drop_column("extraction_error")
        batch_op.drop_column("text_low_confidence")
        batch_op.drop_column("text_char_count")
        batch_op.drop_column("extractor")
        batch_op.drop_column("extracted_at")
        batch_op.drop_column("extraction_claimed_by")
        batch_op.drop_column("extraction_claimed_at")
        batch_op.drop_column("extraction_attempts")
        batch_op.drop_column("extraction_state")

    # ### end Alembic commands ###
